before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng"
script:
- mkdir _build
- sh compile-bibtex.sh
deploy:
  provider: releases
  api_key:
    secure: aabcaf4c1827e71783fc8f7fc5e559a8c251816 
  file:
  - main.pdf
  skip_cleanup: true
  on:
    tags: true
